name: CI/CD - API Gateway
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Deliveroo.Gateway

      - name: Build project
        run: dotnet build Deliveroo.Gateway --no-restore --configuration Release
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t vidura12/deliveroo-gateway:latest ./Deliveroo.Gateway
          docker tag vidura12/deliveroo-gateway:latest vidura12/deliveroo-gateway:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push vidura12/deliveroo-gateway:latest
          docker push vidura12/deliveroo-gateway:${{ github.sha }}